### ISSUE TITLE
Is this a stand-alone plugin or does it require another plugin to work?

### ISSUE THREAD

**Issue by seanhelmes** [justinwhall/ACH-for-stripe-plaid#1]
I have a stripe and plaid account. After entering the correct API credentials on the admin screen of your plugin what do you need to do on the front-end to execute an ACH transaction? Do I simply just need to add a plaid link on my site at this point, or does your plugin require having WooCommerce or something like that to work?

**Comment by justinwhall** [comment]
HI Sean, it's stand alone. It's actually been submitted and approved to be added to the WordPress plugin repository - I just have not gotten around to writing up some docs and uploading.

**Comment by seanhelmes** [comment]
Nice work! Can you tell me how to get your plugin working to set up and charge a fixed price transaction? Is it as simple as adding a plaid link to my site as documented here after I enter my API credentials in your plugin's admin page? https://plaid.com/docs/quickstart/#introduction

**Comment by justinwhall** [comment]
The plugin basically creates the plaid link without having to get involved with all the code on that page. Simply include `[wp_stripe_plaid]` shortcode on the page you wish to accept payments on and it will render the payment form and plaid link.
